"""Catalog of everything shown in 编曲交付中心 (the pinned delivery page).

One entry per work. `ref` is the git ref the files come from (None = the
current working tree, i.e. the song you just built in this session).
`src` is the folder whose files go into the download zip.

Standard songs (layout="standard") get a zip laid out as
    <title>_编曲交付/说明.txt
    <title>_编曲交付/1_四样主文件/   the four must-have files
    <title>_编曲交付/2_其他文件/     everything else from src
Works with their own folder structure (layout="keep") are zipped as-is,
plus 说明.txt; `extra` adds files from elsewhere into a subfolder.

`main` maps the four deliverables to file names inside src (None = missing):
    musicxml  西贝柳斯工程      pdf    总谱 PDF
    strings   弦乐总 MIDI       vocal  人声带歌词 MIDI
An instrumental work has no vocal MIDI: give it `parts` (分谱 PDF) instead,
plus `other_note` (what 2_其他文件 holds) and `howto` (the ACE line of
说明.txt).
To add a new song: append an entry here (newest work at the top is fine,
the page sorts by `updated`), then run tools/deliver/package.py <slug>.
"""

WORKS = [
    dict(
        slug="juebieshu", section="song", ref="origin/claude/determined-galileo-0epaj3",
        title="诀别书", subtitle="全曲 · 弦乐五重奏",
        artist="", key="F 大调（原调，d 小调色彩）", tempo="♩=112",
        instrumentation="弦乐五重奏（邓垚钢琴曲）",
        src="干活/诀别书", layout="keep",
        main=dict(musicxml="1_西贝柳斯工程/诀别书_弦乐五重奏.musicxml",
                  pdf="2_总谱与分谱PDF/诀别书_弦乐五重奏_总谱.pdf",
                  strings="3_ACE_Studio_MIDI/诀别书_弦乐五重奏_全轨.mid",
                  parts="2_总谱与分谱PDF/诀别书_弦乐五重奏_全部分谱.pdf"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="纯器乐曲，没有人声。压缩包就是按用途分好的成品文件夹，先看里面的「使用说明.md」。总谱 11×17 带封面和「花开当富贵」署名，用 LilyPond 排版。全曲 52 小节，约 2 分钟。",
        howto=["ACE Studio：在第 1 小节导入「3_ACE_Studio_MIDI/诀别书_弦乐五重奏_全轨.mid」（五条轨），保留速度信息，每轨加载 String Section，speaker 依次选 Violins I / Violins II / Violas / Celli / Basses。没有用拨弦和弱音器，演奏法保持智能模式。",
               "第 40 小节第 4 拍五条轨同时休止一拍（G.P.），是有意的，不要补音。"],
        questions=[]),
    dict(
        slug="dongfeng", section="song", ref=None,
        title="冬风", subtitle="全曲 · 弦乐四重奏 · 肖邦练习曲 Op. 25 No. 11",
        artist="", key="a 小调（原调）", tempo="二分音符=69（♩=138）",
        instrumentation="弦乐四重奏 · 纯器乐（肖邦 a 小调练习曲「冬风」）",
        src="dongfeng/output", layout="standard",
        main=dict(musicxml="冬风_弦乐四重奏.musicxml",
                  pdf="冬风_总谱.pdf",
                  strings="冬风_弦乐四重奏_全轨.mid",
                  parts="冬风_分谱.pdf"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="纯器乐，没有人声：四样主文件是西贝柳斯工程、好莱坞总谱 PDF（封面 + 12 页）、弦乐总 MIDI 和分谱 PDF。全曲 96 小节，约 3 分 05 秒。肖邦的每个音都和你给的 17 页钢琴谱逐一核对过。",
        other_note="「1_四样主文件」是西贝柳斯工程、总谱 PDF、弦乐总 MIDI 和分谱 PDF，「2_其他文件」里是每件乐器单独的 MIDI 和试听 mp3。",
        howto=["ACE Studio：在第 1 小节导入弦乐总 MIDI（四条乐器轨，保留速度信息），每轨加载 String Section，speaker 选 Violins I / Violins II / Violas / Celli（想要更独奏的声音就选单把的小提琴、中提琴、大提琴）。没有弱起，ACE 第 N 小节 = 总谱第 N 小节。",
               "谱上的 sul tasto（1–4 小节）、sul ponticello（65–68）、震音（59–60 大提琴，62、64 中提琴和大提琴，66–68）、跳弓（81–84 第一小提琴）在 MIDI 里是普通音符或重复的三十二分音符，需要的话在 ACE 里手动选演奏法。想一轨一轨导入，就用「2_其他文件」里的分轨 MIDI。"],
        questions=[
            "调保留原调 a 小调（A、E、D、G 空弦都能共鸣）。要换调告诉我。",
            "速度按肖邦的二分音符 = 69，弦乐四重奏拉这首非常吃力；要给真人乐手演，可以放慢到 60–63。",
            "第 16 小节第 4 拍第一个音，两份谱都没写还原号，这里按半音阶上行写成 D 还原。你的版本明确是 D♭ 的话告诉我。",
            "结尾第 95 小节：肖邦是双手八度、四个八度的音阶。这里改成四件乐器同时从各自的 C 起、一人两个八度，合起来仍是四个八度，落到最后的 A 和弦。想要照原样一件接一件，告诉我。",
        ]),
    dict(
        slug="wohewodezuguo", section="song", ref=None,
        title="我和我的祖国", subtitle="全曲 · 四声部独唱与弦乐四重奏",
        artist="李谷一", key="♭E 大调（原谱调）", tempo="♩.=56",
        instrumentation="S.A.T.B. 四声部独唱 + 弦乐四重奏",
        src="wohewodezuguo/output", layout="standard",
        main=dict(musicxml="我和我的祖国_全曲_四声部人声弦乐四重奏.musicxml",
                  pdf="我和我的祖国_全曲_总谱.pdf",
                  strings="我和我的祖国_弦乐四重奏_伴奏.mid",
                  vocal="我和我的祖国_四声部人声_带歌词.mid"),
        labels=dict(vocal="四声部人声带歌词 MIDI"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="四个声部各一位歌手（单人合唱）。先看压缩包里的「使用说明.md」：ACE 导入、拨弦位置、气口 br、多音字。",
        questions=[
            "第一段主歌交给女低音独唱（旋律 ♭B3–F5 正好在她的音区），女高音留到副歌「我最亲爱的祖国」才第一次开口。想让女高音从头唱，告诉我。",
            "歌词：原谱第 54 小节印的「浪的忧愁」按通行歌词唱成「海的忧愁」。第 27 小节「紧贴着」（常见是「紧依着」）、第 11–12 小节「分隔」（常见是「分割」）照原谱没改，要改告诉我。",
            "速度定的是附点四分音符 = 56（Moderato）。想贴合某个录音的速度，告诉我。",
            "每个乐句前有一个歌词为 br 的短音标换气。如果 ACE 把它唱成字，删掉这些短音即可。",
        ]),
    dict(
        slug="unravel", section="song", ref=None,
        title="Unravel", subtitle="全曲 · 弦乐四重奏 · 东京喰种 OP · 依 Animenz 钢琴版改编",
        artist="TK from 凛として時雨", key="g 小调（原调）", tempo="♩=134",
        instrumentation="弦乐四重奏 · 纯器乐",
        src="unravel/output", layout="standard",
        main=dict(musicxml="Unravel_全曲_弦乐四重奏.musicxml",
                  pdf="Unravel_全曲_总谱.pdf",
                  strings="Unravel_弦乐四重奏.mid",
                  parts="Unravel_分谱.pdf"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="纯器乐，没有人声：四样主文件是西贝柳斯工程、好莱坞总谱 PDF（封面 + 15 页）、弦乐总 MIDI 和分谱 PDF。全曲约 3 分 57 秒。",
        other_note="「1_四样主文件」是西贝柳斯工程、总谱 PDF、弦乐总 MIDI 和分谱 PDF，「2_其他文件」里是试听 mp3。",
        howto=["ACE Studio：在第 1 小节导入弦乐总 MIDI（四条乐器轨），每轨加载 String Section（有独奏小提琴、中提琴、大提琴就用独奏的）。MIDI 开头空一小节，弱起在它的最后一个八分音符上，ACE 的第 N 小节 = 总谱第 N−1 小节。",
               "总谱第 78–81 小节（ACE 第 79–82 小节）的震音在 MIDI 里写成了快速重复音；ACE 有 tremolo 演奏法的话，可以改成长音再选 tremolo。"],
        questions=[
            "八音盒段（第 90–96、129–130 小节）钢琴原谱在 8va 下最高到 G7，小提琴拉不到，这里第一小提琴整体低八度拉，旋律形状不变。",
            "终副歌第 112 小节用了 fff（钢琴原谱是 ff），让最后一次副歌成为全曲顶点；不要的话改回 ff。",
        ]),
    dict(
        slug="alla-turca", section="song", ref=None,
        title="土耳其进行曲", subtitle="全曲 · 弦乐四重奏",
        artist="", key="a 小调 / A 大调（原调）", tempo="♩=120",
        instrumentation="弦乐四重奏（莫扎特 K.331 第三乐章）",
        src="alla-turca/output", layout="standard",
        main=dict(musicxml="土耳其进行曲_弦乐四重奏.musicxml",
                  pdf="土耳其进行曲_总谱.pdf",
                  strings="土耳其进行曲_弦乐四重奏.mid",
                  parts="土耳其进行曲_分谱.pdf"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="纯器乐曲，没有人声：四样主文件是西贝柳斯工程、好莱坞总谱 PDF、弦乐总 MIDI 和分谱 PDF。反复全部写开，第二遍换配器，全曲约 3 分 44 秒。",
        other_note="「1_四样主文件」是西贝柳斯工程、总谱 PDF、弦乐总 MIDI 和分谱 PDF，「2_其他文件」里是试听 mp3。",
        howto=["ACE Studio：在第 1 小节导入弦乐总 MIDI（四条乐器轨），每轨加载 String Section。MIDI 开头空一拍，ACE 的第 N 小节 = 总谱第 N−1 小节。",
               "拨弦（pizz.）要在 ACE 里把演奏法改成 Pizzicato（ACE 小节号）：Violin I 74–81、106–108；Violin II 74–81、106–112；Viola 10–16、42–49、58–65、122–129、138–144、170–177；Violoncello 10–17、42–49、58–65、74–81、106–113、122–129、138–145、170–177。"],
        questions=[
            "谱上 m52（总谱第 92、108 小节）第 6 个十六分音符是 B♯5，原典版是 D6；m55（第 95、111 小节）第 4 个音是 F♯5，原典版是 A5。现在照你给的谱，要改成原典版告诉我。",
            "速度按 Allegretto ♩=120，反复全部保留（约 3 分 44 秒）。想要更快或少几遍反复告诉我。",
            "拨弦段落在 ACE 里要手动改成 Pizzicato，小节号写在压缩包的说明.txt 里。",
        ]),
    dict(
        slug="wobunanguo", section="song", ref=None,
        title="我不难过", subtitle="副歌 · 人声与弦乐四重奏",
        artist="孙燕姿", key="♭E 大调", tempo="♩=68",
        instrumentation="人声 + 弦乐四重奏",
        src="wobunanguo/output", layout="standard",
        main=dict(musicxml="我不难过_副歌_人声弦乐四重奏.musicxml",
                  pdf="我不难过_副歌_总谱.pdf",
                  strings="我不难过_弦乐四重奏_伴奏.mid",
                  vocal="我不难过_人声_带歌词.mid"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        questions=[]),  # 用户说这首不用再重做，别再问
    dict(
        slug="qingge", section="song", ref="origin/claude/serene-darwin-2l4jy4",
        title="情歌", subtitle="最后一遍副歌 · 人声与弦乐四重奏",
        artist="梁静茹", key="F 大调", tempo="♩=70",
        instrumentation="人声 + 弦乐四重奏",
        src="qingge/output", layout="standard",
        main=dict(musicxml="情歌_副歌_人声弦乐四重奏.musicxml",
                  pdf="情歌_总谱.pdf",
                  strings="情歌_弦乐四重奏_伴奏.mid",
                  vocal="情歌_人声_带歌词.mid"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        note="总谱 PDF 带封面和「花开当富贵」署名，是 A4 版式（LilyPond 排的），还不是统一的 11×17 好莱坞模板。",
        questions=[
            "简谱整段写在高音点上，这里按实际演唱放到 C4–C5 八度，请核对。",
            "「可是」写成 C4→D4 再接「那」F4，请核对。",
            "「久」按原谱只唱 2 拍，弦乐第 3 拍接尾奏，请确认。",
        ]),
    dict(
        slug="chatang", section="song", ref=None,
        title="茶汤", subtitle="副歌 · 人声与弦乐四重奏",
        artist="郁可唯", key="A 大调（原调）", tempo="♩=112",
        instrumentation="人声 + 弦乐四重奏",
        src="chatang/output", layout="standard",
        main=dict(musicxml="茶汤_副歌_人声弦乐四重奏.musicxml",
                  pdf="茶汤_副歌_总谱.pdf",
                  strings="茶汤_弦乐四重奏_伴奏.mid",
                  vocal="茶汤_人声_带歌词.mid"),
        pdf_kind="hollywood", audio="粗略试听_GM音色_非ACE效果.mp3",
        questions=[
            "调没指定，这版保留原调 A 大调（人声 C#4–E5）。要换调告诉我。",
            "转写时中音区 1 记作 A3，请核对八度。",
            "「的」「冷」「在」上的波音只记在谱上，MIDI 里没展开，需要的话在 ACE 里画音高曲线。",
        ]),
    dict(
        slug="dadongbei", section="song", ref="origin/claude/determined-archimedes-93zrgx",
        title="大东北我的家乡", subtitle="全曲 · 迪士尼风格交响乐 + SATB 合唱",
        artist="何玉", key="F 大调 → G 大调", tempo="♩=72 / ♩=128",
        instrumentation="交响乐队（Instrument X）+ 四声部合唱",
        src="干活/大东北我的家乡", layout="keep",
        extra={"4_试听与字幕": [
            "dadongbei/output/粗略试听_GM音色_非最终效果.mp3",
            "dadongbei/output/大东北我的家乡_歌词字幕.srt",
            "dadongbei/output/大东北我的家乡_交响合唱_全轨.mid"]},
        main=dict(musicxml="3_西贝柳斯总谱_好莱坞C调格式/大东北我的家乡_好莱坞总谱_西贝柳斯用.musicxml",
                  pdf="3_西贝柳斯总谱_好莱坞C调格式/大东北我的家乡_好莱坞C调总谱_预览.pdf",
                  strings="1_InstrumentX乐队MIDI/00_全乐队15轨_InstrumentX.mid",
                  vocal="2_合唱四声部合并_带歌词MIDI/大东北我的家乡_合唱四声部合并_带歌词.mid"),
        labels=dict(strings="乐队总 MIDI", vocal="合唱带歌词 MIDI"),
        pdf_kind="preview", audio="4_试听与字幕/粗略试听_GM音色_非最终效果.mp3",
        note="压缩包就是按用途分好的成品文件夹，先看里面的「使用说明.md」。",
        questions=[
            "Instrument X 导入 MIDI 时读不读速度变化（看第 5 小节是不是 ♩=128）？不读就用「按秒对齐_固定120BPM_备用」那套。",
            "西贝柳斯打开后，A 调单簧管、F 调圆号、降 B 调小号等移调乐器显示是否正常？",
            "现在唱一遍主歌、两遍副歌（第二遍转 G），要不要照原谱整首唱两遍？",
            "ACE 里多音字要核对：长、模、呐、血、着、地、这。",
        ]),
    dict(
        slug="leihai", section="song", ref="origin/main",
        title="泪海", subtitle="副歌 · 人声与弦乐四重奏",
        artist="许茹芸", key="F 大调", tempo="♩=59",
        instrumentation="人声 + 弦乐四重奏",
        src="leihai/output", layout="standard",
        main=dict(musicxml="泪海_副歌_人声弦乐四重奏.musicxml",
                  pdf="泪海_副歌_总谱预览.pdf",
                  strings="泪海_弦乐四重奏_伴奏.mid",
                  vocal="泪海_人声_带歌词.mid"),
        pdf_kind="preview", audio="粗略试听_GM音色_非ACE效果.mp3",
        questions=[]),
    dict(
        slug="jiayibingding", section="song", ref="origin/claude/loving-bell-wsnmgy",
        title="甲乙丙丁", subtitle="副歌 · 人声与弦乐五重奏",
        artist="李佳薇", key="F 大调", tempo="♩=65",
        instrumentation="人声 + 弦乐五重奏",
        src="jiayibingding/output", layout="standard",
        main=dict(musicxml="甲乙丙丁_副歌_人声弦乐五重奏.musicxml",
                  pdf="甲乙丙丁_副歌_总谱预览.pdf",
                  strings="甲乙丙丁_弦乐五重奏_伴奏.mid",
                  vocal="甲乙丙丁_人声_带歌词.mid"),
        pdf_kind="preview", audio="粗略试听_MuseScore音色_非ACE效果.mp3",
        questions=[
            "副歌暂取「你我怎么两清」到「能否换来一点同情」。如果你要的范围不同（比如还包括「是你教我勇敢……」），告诉我补进去。",
        ]),
    dict(
        slug="jasmine", section="song", ref="origin/claude/sleepy-wozniak-g09dmt",
        title="茉莉花", subtitle="全曲 · 人声与弦乐五重奏",
        artist="江苏民歌", key="F 大调", tempo="♩=76",
        instrumentation="人声 + 弦乐五重奏",
        src="jasmine-flower", layout="keep", include=["茉莉花_人声与弦乐五重奏.mxl"],
        main=dict(musicxml="茉莉花_人声与弦乐五重奏.mxl", pdf=None,
                  strings=None, vocal=None),
        pdf_kind=None, audio=None,
        note="只有一个西贝柳斯能直接打开的 .mxl 总谱，还没有 PDF 和 MIDI。",
        questions=[]),
    # ---- 视频与动画 --------------------------------------------------------
    dict(
        slug="guoqing-video", section="media", ref=None,
        title="我和我的祖国 · 国庆抖音版", subtitle="竖屏 83 秒（歌曲 1:32 到结尾）· 手写谱逐字同步",
        artist="", key="", tempo="", instrumentation="",
        src="wohewodezuguo/video/成片", layout="keep",
        main={}, pdf_kind=None, audio=None, video="我和我的祖国_国庆版_竖屏.mp4",
        note="可以直接发抖音。压缩包里有封面图和「发布说明.txt」（标题、简介、话题、发布时间）。发布时在「高级设置 → 作者声明」勾选「内容由 AI 生成」。",
        questions=[]),
    dict(
        slug="dengchao", section="media", ref="origin/claude/elegant-pascal-83rncr",
        title="《等潮》视频制作包", subtitle="泪海 · 抖音竖屏 · TapNow 分镜与提示词",
        artist="", key="", tempo="", instrumentation="",
        src="leihai/video/tapnow", layout="keep",
        main={}, pdf_kind=None, audio=None,
        note="先打开「分镜与提示词.md」：照着在 TapNow 里生成 28 个镜头，放进 clips 文件夹，再运行 assemble.py 合成。",
        questions=[]),
    dict(
        slug="clawd", section="media", ref="origin/claude/loving-bell-wsnmgy",
        title="甲乙丙丁 · Clawd 动画样片", subtitle="10 秒样片（歌曲 0:28–0:38）",
        artist="", key="", tempo="", instrumentation="",
        src="jiayibingding/video/clawd", layout="keep",
        main={}, pdf_kind=None, audio=None, video="样片_Clawd_0m28-0m38.mp4",
        questions=["要不要把这 10 秒样片扩展成完整视频、用哪种画风，还在等你定。"]),
    dict(
        slug="pianopet", section="media", ref="origin/claude/focused-volta-ve5ka6",
        title="小 Claude 弹钢琴", subtitle="5 秒循环动画",
        artist="", key="", tempo="", instrumentation="",
        src="claude-piano-pet", layout="keep",
        main={}, pdf_kind=None, audio=None,
        note="解压后双击 index.html，用浏览器打开就能播放。",
        questions=[]),
]
